### ISSUE TITLE
Create A Sign Up Form

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#1]
This will be where _anyone_ can go to sign up for an account, regardless of whether they are registering for a race at the moment or not.

This form should require the same fields required during registration for a race:

 - Email
 - Password
 - First, Last, Cell, DOB, Address, etc

After signing up, I expect to be redirected to a specific screen until I confirm my account.

The purpose of this form is to give people the ability to create an account outside of registering for a race. Once they have an account, we will be able to match registrations/participations ot this user via the email address they use.

**Comment by ColinW520** [comment]
I am choosing to leave off the address part. It makes the form way too big. We can get that during registrations when needed.

Desktop
![image](https://user-images.githubusercontent.com/3529146/54453763-fc135c00-4725-11e9-8caf-802f8ef3354e.png)

Mobile
![image](https://user-images.githubusercontent.com/3529146/54454028-8a87dd80-4726-11e9-9edc-63520164d098.png)

@runbeyond what are your thoughts on the verbiage?

**Comment by runbeyond** [comment]
This looks awesome!

I would slightly modify the verbiage on the above screen to read: Anyone can create an account! It makes it much easier to register for future races, manage your races, see historical races and results, and plan your racing schedule! Account holders also have access to exclusive offers."

@ColinW520 what do you think?

**Comment by ColinW520** [comment]
Signup link is here:

https://www.spectrumtrailracing.com/users/sign_up

Verbiage updated in b5f1f05b6f12a12785c9f0395e95030baa16c8d3

**Comment by ColinW520** [comment]
@runbeyond ready to close this one now! to test, you will need to be signed out. This issue _only_ covers the sign up form itself; not the flow (aka -- anything that happens _next_)

**Comment by runbeyond** [comment]
Nice work, @ColinW520! 

I like the aesthetic and we're capturing the perfect amount of information at this point. There is really no need for us to capture address information for our customers. We just need city and state in the registration process which we have.

Ther eerror messages in the sign up process work well and it was easy to find where I made an error.

A couple of issues I noticed:

1) Once I created the account, I received a banner notification saying that I need to create an account or sign in. 

2) I signed in and landed on the admin dashboard page indicating that I was assigned admin access when I created my account (I suspect I somehow got logged in with my jasonclimbs@gmail.com credentials). I used my jason@spectrumtrailracing.com address to create my new account. My current account (admin account) is associated with jasonclimbs@gmail.com

3) I opened the confirmation email I received. I opened it on my mobile device. I clicked on the link to confirm my email address (keep in mind that at this point I already signed on the web app after creating the account). This took me to the account sign in page. I signed in with my new credentials and checked the remember me box. Upon signing in I received the 500 error message. I clicked on the button "GO TO OUR HOMEPAGE" and when I landed on the homepage, I go a banner notification stating that I successfully signed in. To test this out further, I clicked on the menu and saw the admin dashboard link. I clicked on the link and received an error message that only Spectrum admins are allowed to access the admin dashboard.

4) I logged out of my account in the web app and tried logging again with my new credentials and received the attached 422 error message.

Let me know if you need more info!
<img width="1340" alt="Screen Shot 2019-08-21 at 2 24 56 PM" src="https://user-images.githubusercontent.com/44638093/63462165-e7976600-c41f-11e9-9ea4-09f155da0f32.png">

**Comment by ColinW520** [comment]
@runbeyond here is the current flow:

1) fill out that form
2) get an email like this:
![image](https://user-images.githubusercontent.com/3529146/70879155-95a3be80-1f81-11ea-83d6-10986132d62f.png)

3) click on that link
4) see this message
![image](https://user-images.githubusercontent.com/3529146/70879186-a94f2500-1f81-11ea-8967-2c02e8ef399b.png)


5) see this (intentional) 500

![image](https://user-images.githubusercontent.com/3529146/70879236-d26fb580-1f81-11ea-8873-e08a7925d5f0.png)

**Comment by runbeyond** [comment]
Thanks, @ColinW520 This looks awesome so far.
