### ISSUE TITLE
Registration Banner Messages

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#100]
On the Sky Island page, the registration banner reads that Sky Island is sold out for this year. This is confusing because Sky Island is over for this year and thus when a user visits the page to learn about registration for 2020 they think that 2020 is already sold out. 

Based on my understanding of the logic around the banner message, and the given that we have set the 2020 dates for the race, registration opening, and registration closing, I would expect that banner message reads that registration for the 2020 sky island race opens march 1st, 2020.

**Comment by ColinW520** [comment]
This is not a bug, per-se. We will need to create new **Race** records, because the 2019 records are of course, still sold out.

**Comment by runbeyond** [comment]
Closing this as problem is solved now that we have ability to archive and duplicate races.
