### ISSUE TITLE
Contact email on Registration Confirmation Email

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#101]
On the bottom of the registration email, there is a contact email listed as contact@spectrumtrailrunning.com which is not a real email address.

Please replace this with either malloryalexis@gmail.com or mallory@spectrumtrailracing.com

**Comment by ColinW520** [comment]
Not a feature as this is aberrant behavior/information that needs replaced.

Went through the codebase to  make sure there were no remaining references to contact@spectrumtrailracing.com

**Comment by runbeyond** [comment]
Thanks, Colin!
