### ISSUE TITLE
Add ecommerce tracking to Google Analytics

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#105]
I would like to add ecommerce tracking to our google analytics implementation so that we can better track revenue and conversations on our super awesome website in order to make it even better!

Here is the developer guide to implementing ecommerce tracking: https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

**Comment by ColinW520** [comment]
I would want to do this server-side. Will need to research.

**Comment by ColinW520** [comment]
https://github.com/railslove/rack-tracker

**Comment by runbeyond** [comment]
That was a great read! They have detailed solutions for analytics advanced ecommerce, and tag manager, all of which would be great to have for a complete analytics package. They also have instructions for adding Facebook Pixel which would set us up really well!

What else can I do to support?

**Comment by willblake01** [comment]
Colin has rack-tracker setup but the google e-commerce configuration needs some attention.

![image](https://user-images.githubusercontent.com/16193879/95690431-5d8afd80-0bdd-11eb-9b6c-f70b6845f9fb.png)

**Comment by willblake01** [comment]
@runbeyond Just to clarify we're trying to capture e-commerce tracking for race registrations from the main site correct?

**Comment by runbeyond** [comment]
@willblake01 @ColinW520 

We're moving in a different direction on this one so I am closing this issue as no longer relevant.
