### ISSUE TITLE
add the ability to archive a race

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#107]
Right now, races are hidden/shown by `active` boolean. Once a race is completed, we need to mark it as such. Remember the hierarchy:

Locations
    -- Events
        ---- Races
           ---- Registrations
               ---- Participants

Archived races do not impact registerability.

**Comment by ColinW520** [comment]
Requirement:

For search, display, and start list purposes, when you archive a race, registrations associated with that race are also archived.

**Comment by ColinW520** [comment]
@runbeyond besides #113 , can you think of anything else that needs to be done around archiving races / registrations right now?

**Comment by runbeyond** [comment]
Nothing comes immediately to mind which means it's nice and simple and we should run with it!

**Comment by runbeyond** [comment]
Thanks @ColinW520 This works great!

**Comment by runbeyond** [comment]
Thanks @ColinW520! This works great!
