### ISSUE TITLE
Participant Record Editing Bug

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#109]
Use case context:

Participant #850 wants to move from The Circus 30k to 10k. The participant record doesn't include inputs for address, phone, emergency contact, or medical conditions. When trying to edit the participant record, the system throws error message that those data fields cannot be empty. 

Is it possible this registration record was created prior to resolving the root problem (where participant can register without inputting those data fields)? 

Anyway, I am going to reach out to participant to get the rest of the participant record data so we can update accordingly.

**Comment by ColinW520** [comment]
@runbeyond can confirm this participant was created before the most recent attempt to fix this bug. we can close this.
