### ISSUE TITLE
Show/hide archived race records in admin dashboard

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#113]
Please add capability to show/hide archived races in the admin dashboard.

**Comment by runbeyond** [comment]
I don't see how to hide/show archived races. Am I looking in the right place?
<img width="1428" alt="Screen Shot 2019-12-09 at 8 11 09 PM" src="https://user-images.githubusercontent.com/44638093/70489020-1e24e980-1ac0-11ea-9ac0-b44c3d8bc91d.png">

**Comment by ColinW520** [comment]
@runbeyond -- if you scroll to the bottom of the page at admin/races, you should see a link

**Comment by ColinW520** [comment]
![image](https://user-images.githubusercontent.com/3529146/70878368-735c7180-1f7e-11ea-951d-ed84d0e6d53f.png)

**Comment by runbeyond** [comment]
Thanks, @ColinW520! This is great progress! I opened a new issue (#116 ). Please check it out.
