### ISSUE TITLE
Duplicate/Archived races show in Admin dashboard UI and race registration UI

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#116]
Now that we have been archiving and duplicating race records, we see that that duplicate races show up in UI elements in the admin dashboard and on the race registration pages. Please see attached 
<img width="1440" alt="Screen Shot 2019-12-16 at 8 35 00 AM" src="https://user-images.githubusercontent.com/44638093/70915353-5015de80-1fdf-11ea-82f2-60f803426ab2.png">
<img width="1180" alt="Screen Shot 2019-12-16 at 8 33 42 AM" src="https://user-images.githubusercontent.com/44638093/70915364-52783880-1fdf-11ea-9f94-5ac2dca224c3.png">

screenshots.

**Comment by ColinW520** [comment]
I will have a fix out for this shortly.

**Comment by ColinW520** [comment]
@runbeyond --in the meantime, you could simply mark the old races as 'inactive' -- that is your master control. I will add a scope here for archived as well.

**Comment by runbeyond** [comment]
Ok. I didn't realize. Let me try that. I don't want to invest any work in this if I can just mark the race inactive manually.

**Comment by runbeyond** [comment]
Unflagging the race as active solves the issue in one of three places. See screenshots.

<img width="1026" alt="Screen Shot 2019-12-16 at 11 42 11 AM" src="https://user-images.githubusercontent.com/44638093/70929652-2b2e6500-1ff9-11ea-900c-9b5740965775.png">
<img width="1189" alt="Screen Shot 2019-12-16 at 11 42 04 AM" src="https://user-images.githubusercontent.com/44638093/70929659-2e295580-1ff9-11ea-837c-abb398ebd918.png">

**Comment by ColinW520** [comment]
@runbeyond my last deploy should have resolved this issue in the admin as well

**Comment by ColinW520** [comment]
@runbeyond ^ scratch that, resolving now with new commit

**Comment by runbeyond** [comment]
Thanks, @ColinW520! This looks great!!
