### ISSUE TITLE
Return from Team Member page to Race Team landing page

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#117]
It would be great to have an easy and obvious way to return from an individual team member's page to the race team landing page.

For example, I click the profile button and individual team member profile is a pop up screen that can be x'd out. Or there is an 'x' or return button or something like that on the individual team member page.

I leave to you guys to solve the problem!

**Comment by ColinW520** [comment]
Sure thing, we can add a link to the bottom of the profile, and the top.

**Comment by ColinW520** [comment]
I would really like to avoid modals / pop-ups for content rendering purposes. That opens a big bag of worms.

**Comment by runbeyond** [comment]
Sounds good! Thanks.

**Comment by ColinW520** [comment]
@willblake01 -- this one is for you!

 - [ ] at the bottom of the page, after the existing content, at the center of the page add a link to `team_members_path` with the text `Back to Roster`

 - [ ] immediately beneath the jumbotron header, before the page content, left adjusted, add a link to `team_members_path` with the text `Back to Roster`

**Comment by runbeyond** [comment]
I’m game!

**Comment by willblake01** [comment]
<img width="563" alt="Screen Shot 2019-12-20 at 5 14 06 PM" src="https://user-images.githubusercontent.com/16193879/71298249-da966f00-234c-11ea-95f4-df554b389257.png">

@runbeyond @ColinW520 What do you guys think about a previous & next button from the individual card to scroll through members without going back to the team screen? In addition to the back to roster button?

**Comment by willblake01** [comment]
Or like previous athlete/next athlete or something....

**Comment by ColinW520** [comment]
If there were an order of Team members defined, ie first then last, then previous/next would make sense.... but without that, how would you define who the 'next' team member would be

**Comment by willblake01** [comment]
I think right now it's using the id. Maybe it makes more sense to scroll through only leaders & only team members depending on which the end user clicked on?

**Comment by runbeyond** [comment]
Let's just stick with return to previous screen for now. I think we can close out the team pages for a while once we close out this issue.

**Comment by runbeyond** [comment]
Didn't meant to close that.

**Comment by ColinW520** [comment]
#129 resolves this (when merged)

**Comment by ColinW520** [comment]
@willblake01 should've given you a heads up on this: Don't close issues! @runbeyond, our noble project manager, closes out issues for us once he confirms he is satisfied with the resolution.

**Comment by ColinW520** [comment]
Right now, our proccess is to add the 'Needs Approval' label, and assign to @runbeyond

**Comment by runbeyond** [comment]
I'm placing this back to "In Progress". We need a better solution design for the placement of the back button.

Also, the previous and next buttons (which I didn't think we agreed on implementing) seem to function at random. For example, I scrolled through today and this was the order I was taken through: I started on my profile and then next button moved from me to Steven Moore, to Justin Wendling, to JJ Tiscareno, to Josh Beckham, to Allen Daniel, to Mike Kurvach, to Colin Hagan...

The team member profiles are listed alphabetically but the next button did not move through the team members alphabetically so what is the logic driving this function?

**Comment by willblake01** [comment]
@runbeyond Just to follow up here this is why I mentioned I realized I needed to work from the issue, I realized after the pull request you responded to leave out the prev/next buttons. Sorry, learning as I go. Workflow and team dynamics wasn't something we got experience in at boot camp. Just to clarify the buttons were scrolling by team member id so would need additional work on sorting. I believe the ranked-model gem Colin added could be used for this but that's a discussion for another time. I'm still a little unclear where you'd like the button positioned so let's figure that out and I'll make another PR to ditch the scrolling and get that button where you'd like it.

@ColinW520 Would we just create a new PR when ready or somehow roll back and remove the old merge?

Thanks!

**Comment by willblake01** [comment]
@runbeyond Ok, back at it. I removed the previous/next functionality and moved the back button to the bottom center and changed the text to "Back to Roster". Is this what you had in mind?

![image](https://user-images.githubusercontent.com/16193879/74540760-f742c380-4f05-11ea-8466-11501b5f134b.png)

**Comment by runbeyond** [comment]
@willblake01 That looks good. Thanks! I approve.

**Comment by runbeyond** [comment]
Thanks, @willblake01
