### ISSUE TITLE
Team Member landscape photos

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#118]
The landscape photos on the team member pages crop in an unpredictable way.

My photo worked great: https://www.spectrumtrailracing.com/team/jason-brooks

Whereas Katie Towle's photo did not: https://www.spectrumtrailracing.com/team/katie-towle

Is there a reason for this? Is it a problem we should solve from a development perspective? My concern is that how will I know what kind/size of landscape photo to request from the team so that it doesn't get awkwardly cropped?

**Comment by ColinW520** [comment]
Without getting too deep into the weeds here, its not really cropping anything, its taking the picture exactly as-is. Its the page header (the part with the links) that is creating the cropped effect.

In general, I would recommend iterating with these images. We can add some image manipulation to the backend, and do some variant resizing, dozens of different things -- but all that adds complexity and is a huge time suck that I would recommend we avoid for the time being. 

To restate: In general, **ALL** website content editors have "rules" around photos being uploaded, how they're sized, scaled, etc. I recommend we apply _no_ rules, and let the uploader decide whether or not the end result is what they want.

**Comment by runbeyond** [comment]
Is there a way to add a feature that allows the user uploading photos to choose the focal point for the image?

**Comment by ColinW520** [comment]
No, that would be even more difficult.

**Comment by runbeyond** [comment]
Ok. I will closer this, then.
