### ISSUE TITLE
add results link to main nav

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#122]
Add a link with the text 'results' to the main site nav.

Clicking the link should open a page _on the site_ at /results

The content of this page should include the RaceRoster embeddable.

**Comment by ColinW520** [comment]
Embed code found in #99

**Comment by ColinW520** [comment]
@runbeyond do you foresee any reason this embed code could / would change? Is it something we should make into a variable?

**Comment by runbeyond** [comment]
@ColinW520 I don't foresee it changing. I was thinking that the one calendar could essentially serve as a results database.

**Comment by runbeyond** [comment]
@ColinW520 Here is the embed code I would like to use, please: <iframe src="https://timer.raceroster.com/Calendars/L6crPG2qbgq2eCkzWNVMdUF" id="raceroster" style="border:none; height:800px; width:100%"></iframe>

**Comment by runbeyond** [comment]
This is a great value add. Thank you!
