### ISSUE TITLE
Start List Download does not return complete results

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#123]
The 2019 Circus start list download was incomplete. I had to copy, paste, and format start lists from the web browser for each individual race under the event.

**Comment by ColinW520** [comment]
Can you tell me which records were missing? Or how many? Any pattern to the incompleteness?

**Comment by runbeyond** [comment]
All 30k participants were missing. 17 12-hour solo records were missing. About 2/3 of 10k participants were missing. Maybe a few 12-hour relay participants were missing. I didn’t notice whether anything was missing from the relay, really.

**Comment by ColinW520** [comment]
Looking into it now.

**Comment by ColinW520** [comment]
@runbeyond oh, duh, now I see the problem -- it's because of how Participant search was implemented. fixing now

**Comment by ColinW520** [comment]
Also updating this to make sure we filter out archived registrations.

**Comment by runbeyond** [comment]
Attached is the Goodwater start list and it only shows 8-mile and 16-mile participants. It seems to be missing marathon and double-marathon participants. Will you take a look, please?

[Goodwater-participants-1578423444.pdf](https://github.com/spectrumtrail/spectrum/files/4032035/Goodwater-participants-1578423444.pdf)

**Comment by ColinW520** [comment]
@runbeyond confirmed, I'm seeing this too

**Comment by ColinW520** [comment]
Problem identified: pagination of the index action. Replacing with a dedicated controller action.

**Comment by ColinW520** [comment]
This should be resolved now

**Comment by ColinW520** [comment]
@runbeyond can we mark this as `closed` now?

**Comment by runbeyond** [comment]
Thanks, @ColinW520! This works great now.
