### ISSUE TITLE
Race registration button message

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#132]
Problem statement: when a race sells out (not an event, just an individual race), the registration button on the on the race card on the event page changes from "Register Now" to "Registration Unavailable". Based on user feedback for this specific use case, we hypothesize that the button message would be clearer (and potentially cause less confusion) if it read "Sold Out".

**Comment by ColinW520** [comment]
@runbeyond how does this look now?

**Comment by runbeyond** [comment]
Thanks, Colin! This looks great.
