### ISSUE TITLE
Contact download

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#133]
Problem statement: we communicate with race participants pre and post-race using SendGrid, our email marketing platform. Currently, we capture all participant email addresses on the website through the registration process; however, we do not have a way to extract participant contact details from the website. What we have been doing is copying and pasting the details from the browser on the Registrations page view unique to each event (not a terrible work around, but not ideal).

I'm just spit balling here: A long term vision of awesomeness for this process would be to automate the work by leveraging the SendGrid API to automatically create a contact list in SendGrid for each event each year and feed it with new participant contact details on a daily (or twice daily?) basis. To take it to the next level, it would be sweeeet to have pre-race emails set up in SendGrid as templates so they can be automatically sent to participants on the Monday of race week and then be sent on a one-off basis to each participant that signs up after the Monday of race week (late participants if you will).

In the meantime, I'm wide open to alternative solutions like adding email address to start list download or just having a similar feature to start list download for participant contact download, or whatever else you want to do. It's your solution to define!

If the long-term vision is ever something that approaches reality, we can define the business rules related to issues like email send timing, etc.

**Comment by ColinW520** [comment]
This is all very possible. Let's break this down into bite-size bits though, just to start:

Here's what we can do, today (this week): simply add 'email' to the participants download. That teeny tiny change will make this a lot easier, and won't require a separate controller action/view/download button, etc. One button, multiple functions. If email isn't pertinent to the start list csv that you upload to timing, then simply delete that column.

Here's what we can also do, this month, to start moving toward this vision of automation:
 - go into Sendgrid and create templates for each **EVENT**
 - create a new data model in the app: email_templates, with the following attributes
  - event:belongs_to
  - provider_id:string (this is the ID of the template in sendgrid, generalized in case you ever switch)
  - context:string ['pre-race', 'post-race', 'emergency']
- add columns to 'participant'
  - sent_pre_race_email:boolean
  - sent_post_race_email:boolean
  - sent_emergency_email:boolean
- as we fill out those templates, we assign them to events in the application
- add buttons to each event, "send pre-race email" (etc), which admins can click to send the pre race email to all paid-up participants in non-archived, active races. this button can be re-clicked at any time to send to anyone else who registers late without impacting those to whom it has aready been sent

- once we are comfortable with the semi-manual process (no more copy paste, but, still a button to press), then we can build in biz-logic and background workers to handle it for us automatically.


Overall, this is a medium lift project.

**Comment by ColinW520** [comment]
@runbeyond email is now on the start list download. do you want to create an issue(s) for the rest of this? using the comment above

**Comment by runbeyond** [comment]
Thanks, Colin! I'll open a new ticket now.
