### ISSUE TITLE
Pre-Race and Post-Race Email - Phase 1

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#135]
Here's what we can do, today (this week): simply add 'email' to the participants download. That teeny tiny change will make this a lot easier, and won't require a separate controller action/view/download button, etc. One button, multiple functions. If email isn't pertinent to the start list csv that you upload to timing, then simply delete that column.

Here's what we can also do, this month, to start moving toward this vision of automation:

- go into Sendgrid and create templates for each EVENT
- create a new data model in the app: email_templates, with the following attributes
- event:belongs_to
- provider_id:string (this is the ID of the template in sendgrid, generalized in case you ever switch)
- context:string ['pre-race', 'post-race', 'emergency']
- add columns to 'participant'
    - sent_pre_race_email:boolean
    - sent_post_race_email:boolean
    - sent_emergency_email:boolean

- as we fill out those templates, we assign them to events in the application

- add buttons to each event, "send pre-race email" (etc), which admins can click to send the pre race email to all paid-up participants in non-archived, active races. this button can be re-clicked at any time to send to anyone else who registers late without impacting those to whom it has already been sent

- once we are comfortable with the semi-manual process (no more copy paste, but, still a button to press), then we can build in biz-logic and background workers to handle it for us automatically.

Overall, this is a medium lift project.

**Comment by ColinW520** [comment]
Is this done? I feel like this is done. We have participant email on this download. The rest of this is... many issues.

**Comment by runbeyond** [comment]
Thanks, @ColinW520! This is done. I'm way behind!
