### ISSUE TITLE
Titleize Race Start Lists

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#142]
So that names show cosistenly and accurately

**Comment by willblake01** [comment]
Ok, here's the start list reflecting non-titleized names. You can see that Faron Sagebiel is not titleized.

<img width="821" alt="Screen Shot 2020-02-28 at 3 04 09 PM" src="https://user-images.githubusercontent.com/16193879/75587264-b5ed0080-5a3b-11ea-9fff-b83da9c8841c.png">

**Comment by willblake01** [comment]
Here is after my solution titleizing the name on just the start list view.

<img width="792" alt="Screen Shot 2020-02-28 at 3 04 26 PM" src="https://user-images.githubusercontent.com/16193879/75587423-0ebc9900-5a3c-11ea-9d45-b6d9719ffce6.png">

**Comment by willblake01** [comment]
`%tr
  %td= participant.first_name.titleize
  %td= participant.last_name.titleize
  %td= participant.division.try(:to_s).try(:humanize).try(:titleize)
  %td= participant.race_day_age
  %td= participant.city_and_state
  - if participant.event.allows_teams?
    %td= participant.team_name`

**Comment by runbeyond** [comment]
Thanks, @ColinW520 and @willblake01
