### ISSUE TITLE
Event Page Registration section

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#149]
I'd like to move the Registration section of the event pages to the top of the page. It is currently the second section on the page. Ideally, registration is the primary function of the event page and should thus be the first actionable content on the page. Additionally, registration breaks up the page flow when moving from the overview section to all other sections which it makes it hard for us to create a nice information flow on the pages.

**Comment by willblake01** [comment]
![image](https://user-images.githubusercontent.com/16193879/81870180-f63c2500-953a-11ea-9a22-c0c1292b8dc2.png)
@runbeyond  Ok, I have the registration at the top of the menu and section. Does this look like what you had in mind?
@ColinW520 Is there anywhere else that would need changes that I'm maybe not considering?

**Comment by runbeyond** [comment]
@willblake01 @ColinW520 this looks great! Thanks so much.

**Comment by runbeyond** [comment]
Thank you, @willblake01 and @ColinW520 !
