### ISSUE TITLE
Refunds page data view 

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#157]
As a business administrator, I want to see the name and email address associated with refund records in the admin dashboard so that I can easily cross-reference processed refunds against refund requests to ensure all requests have been processed.

Acceptance criteria:
- when viewing refund records in the admin dashboard, I can see the name and email listed with each refund record
- name and email are listed as the second and third columns in the dashboard view, respectively
- no other changes to the data currently shown in the dashboard view

**Comment by ColinW520** [comment]
@runbeyond deploying these related changes now! please review & close when satisfied.

**Comment by runbeyond** [comment]
This looks great! Thank you team!!
