### ISSUE TITLE
Events seem to be ordering alphabetically

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#16]
@ColinW520 

Events in the admin dashboard and the events cards on the website home page seem to be ordered alphabetically.

Events in the header navigation dropdown list are ordered by race start date/time.

Expected: Events ordered by start date/time in admin dashboard and event cards on homepage sorted by event start/date time.

**Comment by ColinW520** [comment]
This should now be resolved (live coding session)
