### ISSUE TITLE
Newsletter signup mailer view error

### ISSUE THREAD

**Issue by willblake01** [spectrumtrail/spectrum#160]
![image](https://user-images.githubusercontent.com/16193879/89967749-e60a1380-dc17-11ea-9fbc-b66b299c799b.png)

I'm getting this error when trying to render the signup form. This issue is isolated to the mailer, works fine in the application layout.

**Comment by ColinW520** [comment]
This has to do with CSRF tokens. Not a bug! We don't want to render this partial in an email template, really!
