### ISSUE TITLE
BUG - Cannot Update Participant Records

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#163]
As an admin user, I am unable to update participant records. There are three issues related to this problem:

1) When I navigate to a participant record by selecting participants from the main admin dashboard, then search for a participant, then select show registration under actions, then click to edit participant record, the gender selection for the participant record gets cleared.

2) the birth date gets scrambled to a reverse order (from 02/27/1969 to 19/69/0227, for example).

3) once I update the birth date and gender division selection and make the original update I came to make (changing race distance in this case), then click on update participant, I receive an error that the birthdate field can't be left blank.

**Comment by ColinW520** [comment]
@runbeyond -- Github auto-closed this. Can you confirm it is working as expected on PROD?
