### ISSUE TITLE
Price display on race and registration cards

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#169]
We received feedback from several users that is difficult to read the price on the green price icons on race cards on the home page and on registration cards on event and registration pages. 

Let’s please enlarge these to make it easier to read prices.

**Comment by willblake01** [comment]
@runbeyond @ColinW520 I found the way to size the badges was to change the parent element to an h1-h6. I put the options that were meaningfully bigger below, let me know if you have a preference for the size.

![image](https://user-images.githubusercontent.com/16193879/94630713-2ab34200-028c-11eb-85f9-2fa6d1ec4808.png)
![image](https://user-images.githubusercontent.com/16193879/94630850-81208080-028c-11eb-9083-ca7327375acf.png)
![image](https://user-images.githubusercontent.com/16193879/94630854-87166180-028c-11eb-9a50-8e3d51cbf322.png)
![image](https://user-images.githubusercontent.com/16193879/94630860-8c73ac00-028c-11eb-8a1e-6f898c7a8ba0.png)

**Comment by willblake01** [comment]
Here's the events grid:
h1
![image](https://user-images.githubusercontent.com/16193879/94631143-479c4500-028d-11eb-9c88-f773f51d803d.png)
h2
![image](https://user-images.githubusercontent.com/16193879/94631159-51be4380-028d-11eb-90e4-21037088fe64.png)
h3
![image](https://user-images.githubusercontent.com/16193879/94631172-5aaf1500-028d-11eb-8e57-fac7adddbf55.png)
h4
![image](https://user-images.githubusercontent.com/16193879/94631191-626eb980-028d-11eb-805c-e131eeceabff.png)
h5
![image](https://user-images.githubusercontent.com/16193879/94631211-6bf82180-028d-11eb-9750-cd65b58ddc5f.png)

**Comment by willblake01** [comment]
...the badges with the h elements default like above but we could keep them inline like this if preferred.

![image](https://user-images.githubusercontent.com/16193879/94705407-a356e480-0306-11eb-823e-7ebb74c880aa.png)

**Comment by runbeyond** [comment]
Nice work, @willblake01 lets go with h4 on the green badges so they match the similar elements on the page (like the register button) and h3 on the blue badges. 

Can you share a larger screen shot to provide more context?

**Comment by runbeyond** [comment]
This is done. Thanks, @willblake01 and @ColinW520
