### ISSUE TITLE
New registrant email validation

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#17]
Steps to recreate:

1) Start a registration and move to payments page but don't complete the registration
2) Refresh the app or open in a new window
3) Start the registration process again with the same email used previously

**Expected behavior**
Use is able to register without interruption.

**Actual Behavior**
If a user starts but does not complete a registration, and then leaves the application and then returns and starts the registration process over again, the user encounters an error message that their email is already associated with a registration and they are blocked from registering for the event.

**Comment by ColinW520** [comment]
Introducing new behavior to deal with this:

1) removing email validation entirely
2) introducing a new service to handle creation logic. If a registration for the same person/email is already in progress, we will redirect to that registration. if it is complete (paid), we will take them to the 'show' page. If it's brand new, they will continue as usual
3) introducing a 'start_list' page

Let's keep this issue open until that functionality is introduced.

**Comment by ColinW520** [comment]
@runbeyond -- closing this -- it is no longer applicable now that we have the resumable registrations feature.
