### ISSUE TITLE
Expand scope of admin dashboard reports

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#172]
As an admin user and bus manager, I want to see a 6-9 month snapshot of revenue and and registrations. I also want to see charts that reflect recent cancelations and refunds.

**Comment by willblake01** [comment]
Addressed in PR #168.

**Comment by runbeyond** [comment]
@willblake01 This issue is a feature request. Is should thus have an associated PR and must go through the QA and Approval process. In theory, these steps (QA and Approval) should be concluded prior to production release. After that, the Product Manager or Product Owner will close the issue. 

In this context, we are issues in place of user stories.

**Comment by willblake01** [comment]
@runbeyond Gotcha. I linked the PR above but it's already merged into production. Would the ideal workflow be to create a project card and then:

Colin approves PR -> move to QA swim lane (what else happens here? stress testing the feature?) -> move to needs approval -> once approved then merge the PR to production

**Comment by runbeyond** [comment]
That’s a good snapshot of the process. Are you sure this is merged into
production? I didn’t see the changes when I checked about 10 mins ago.

**Comment by willblake01** [comment]
Hmm. I squashed and merged the PR which should have pushed the commit to master but you're right I don't see it for that one. It worked fine for the other 2 PRs and I can see the Codeship build succeeded.

@ColinW520 Did I miss something on that one? 

![image](https://user-images.githubusercontent.com/16193879/95132404-54091d80-0725-11eb-9a75-4af1b1caa0ab.png)

**Comment by willblake01** [comment]
@runbeyond Did this end up deploying ok? I'm guessing it was just the heroku deploy command that needed to run before it merged with production.

**Comment by runbeyond** [comment]
Thanks, @willblake01!
