### ISSUE TITLE
Send a Race Registration Confirmation Email

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#18]
After someone registers for a race, they should receive an email confirming this. This should be _seperate_ from any payment receipt email.

**Comment by ColinW520** [comment]
First round: http://g.recordit.co/LoSoMyun9W.gif

**Comment by ColinW520** [comment]
@runbeyond -- will close issue once this is approved

**Comment by ColinW520** [comment]
Per @runbeyond --

```
Date: Wed, Jun 19, 2019 at 4:21 PM


Hey Colin,

We were working through the website today and didn't get the images load on Mallory's registration confirmation email.

Thanks,
JB

```

**Comment by ColinW520** [comment]
It's working now! See for yourself by trying out a registration.

Note: when we got to prod mode I will need to update an environment variable.

**Comment by runbeyond** [comment]
Thanks,
Colin! This works as expected. The race logo image is a little slow to open with web and mobile experiences but that is a minor issue at this point.
