### ISSUE TITLE
Can't Register for Wonderland, The Circus, or The Game

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#19]
Navigate to the event page and attempt to register for any of the races. 

Expected behavior
Can register

Actual behavior
Cannot click on register or start list buttons

**Comment by ColinW520** [comment]
Ok, I was able to recreate this. It happens on races that don't have images. I will resolve by simplifying the UI.

**Comment by runbeyond** [comment]
Okay. I see. Can I put images in those cards? Do they pull from the race
record? If so, that’s an easy fix!

**Comment by ColinW520** [comment]
They do -- but, it's a design flaw for sure for the buttons not to work without an image

**Comment by ColinW520** [comment]
@runbeyond  -- this is ready to be tested and closed once you've confirmed that you can click on the register button. If other issues, besides being able to click on the button, come up; let's just create a new card.

**Comment by runbeyond** [comment]
Thanks, Colin!
