### ISSUE TITLE
All race dates are off by one day on home page event cards

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#20]
On the home page, under events, the event cards for each event show the event date as one day early despite all event and race records reflected the accurate event date.

**Comment by ColinW520** [comment]
@runbeyond  -- this is ready to be tested. I have now forced all times to display in CST instead of user time zone.

Commit: f52d6d6515a2d5931c204472131ae42ae51a8c3c

**Comment by runbeyond** [comment]
@ColinW520 This bug is related to event dates. Please see attached screenshots from today. In the screenshot from the admin dashboard, you can see that the date is off for the event start date, the registration open date, and the registration close date. In the first screenshot, you can see that the inaccurate date actually shows on the event page.
<img width="1439" alt="Screen Shot 2019-06-20 at 2 44 27 PM" src="https://user-images.githubusercontent.com/44638093/59880385-1e8ec400-936a-11e9-846e-41f7575c6a9f.png">
<img width="1433" alt="Screen Shot 2019-06-20 at 2 46 13 PM" src="https://user-images.githubusercontent.com/44638093/59880558-8d6c1d00-936a-11e9-82c8-1e193b3d6d04.png">

**Comment by ColinW520** [comment]
Things look right to me... TIMEZONES BRO!

Adding granular control over hours for registration windows though....

**Comment by ColinW520** [comment]
@runbeyond I think we can remove blocked from those and close it.

**Comment by runbeyond** [comment]
Thanks, Colin!
