### ISSUE TITLE
Race start times not accurate in admin dashboard

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#21]
When logged into the admin dashboard, the race start time for some events (e.g. Goodwater) reflects one hour earlier than the start time specified in the race record. To recreate this, select edit race and then view the start time selected on the race record as compared to that shown from the dashboard view.

**Comment by ColinW520** [comment]
Ah... timezones... it's showing you those times in your local timezone.

I will need to update to force all times to CDT/CST and include that in the text.

**Comment by runbeyond** [comment]
Interesting...the app is too smart for its own good!

**Comment by ColinW520** [comment]
@runbeyond can you include a link to where specifically you are seeing the race times being off?

**Comment by ColinW520** [comment]
@runbeyond this is now fixed ready to be tested/confirmed. This fix required forcing times to use the event time zone and not the user's time zone.

We will use the user's time zone when representing action time stamps

Commit: 3e44fac4d5a156f9f7c339a87c58027a8a55d83f

**Comment by runbeyond** [comment]
Thanks, Colin! Works as expected.
