### ISSUE TITLE
Update Billing settings for Heroku

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#22]
Sign in to heroku, and go here: https://dashboard.heroku.com/teams/spectrumtrail/billing

![image](https://user-images.githubusercontent.com/3529146/59859645-baa4d500-9342-11e9-92cd-f523d36d153f.png)

**Comment by runbeyond** [comment]
Thanks, Colin! This is done. We can burn up the wire on the Spectrum credit card now.
