### ISSUE TITLE
Scale Production Hosting Environment

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#23]
1 Worker Dyno - $7/mo
1 Web Hobby Dyno - $7/mo
1 'Hobby Basic' Postgres DB - $9/mo
1 Redis 'Nano' instance - Free

The hobby dynos aren't great, performance wise. I could see us needing to bump to professional, but the great thing about Heroku is that we can go up and down without issue, so we will start down.

**Comment by ColinW520** [comment]
@runbeyond  -- do you approve of this setup?

**Comment by runbeyond** [comment]
What is the upside and cost if we go proffesional instead of hobby. I want the site to perform!

**Comment by ColinW520** [comment]
"Pro" dynos start at $25 per month. Maybe we do a pro dyno for the web process; and a hobby dyno for the background worker, since it's really not gonna be working that hard.

**Comment by runbeyond** [comment]
Thanks, Colin. Let me talk to Mallory before I commit to $41/mo for hosting costs.

**Comment by ColinW520** [comment]
Just remember, you can scale as needed.

**Comment by runbeyond** [comment]
Let's start small and scale. Once Mallory sees the site in action, she'll love it and then we can scale as needed for more awesomeness!

**Comment by ColinW520** [comment]
I will do the scaling immediately after the release. We do not need to pre-scale test as this is all Heroku and we don't need the capacity immediately.

**Comment by ColinW520** [comment]
@runbeyond  -- I think we are pretty set here. Good to close?

**Comment by runbeyond** [comment]
Getting shit done! I love it. Thanks, Colin.
