### ISSUE TITLE
Sanitize Old-site Race Registrations

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#24]
Here is the google sheet that's been started:

https://docs.google.com/spreadsheets/d/1eqPGR6YqHp8iMIPj4ZA1Za4cEO7mrBNMopqwTV2sqIE/edit?usp=sharing

We need to add any other registrations, for any other races, on here so we only have to run this import once! I've gotten started filling in data. Here are some notes

 - This will be an all-or-nothing import. If any record fails, it will tell us which one, and then we can deal with that one, and try again.

 - Any missing birth dates will be set to 01/01/1900. There is no 'Age on Race Day' field for participants in the current system. We just use birthdates to calculate that. This may lead to corrections needing to be made.

 - If someone used a discount code, we will add that to the data profile. If they paid, we will store that charge ID. If they bought two registrations on the same charge, each participant will have that charge ID.

 - I tried to extrapolate addresses that were missing. Many were the same as the purchaser in the row above. Some are missing entirely. We will need to spoof those addresses.

 -- More things

**Comment by runbeyond** [comment]
The Google Sheet is up to date. Let me know if we can close this issue and track all of the work on the import script card.

**Comment by ColinW520** [comment]
I've now been through this sheet enough to confirm that I can make it work with what we have. Closing this issue and removing blocking label from #25
