### ISSUE TITLE
Write an import script for registrations from the old Site

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#25]
This script will use the sheet found here (see your email!)

Goal = populate the start list with reasonable accuracy.

**Comment by ColinW520** [comment]
This is blocked until the sheet #24 is complete.

**Comment by runbeyond** [comment]
I don't have edit access to the google sheet so I made all updates in Numbers. The current registrant file is attached. I made sure to input all data fields for address and birthdate. There were a couple of addresses for which I only had city and state info. I put in a fake street address and used a zip code assigned to the reported city of residence.

For missing birthdates, I input a birthdate by using the age on race day to infer the birth year and then assigning 12/1 as the month and day for those birthdays. This way, their age on race day should be accurate on the website. 

[Current Spectrum Registrations_6-22-2019-xlsx.xlsx](https://github.com/spectrumtrail/spectrum/files/3317003/Current.Spectrum.Registrations_6-22-2019-xlsx.xlsx)

**Comment by runbeyond** [comment]
Goog sheet is now current. If we get new registrants in the coming days, I will add them as they come in.

**Comment by ColinW520** [comment]
@runbeyond -- update -- I will need to clear out ALL existing registrations before proceeding with this import, just an FYI

**Comment by runbeyond** [comment]
@ColinW520 et's do it! I'm done testing for now.

**Comment by ColinW520** [comment]
This is _code complete_. I have tested it locally with our csv and it **WORKS**.

HOwever, it is untestable. You can't verify it works; because, registrations are hard to sort through and see granular data through the web UI. 

It will take me 1-2 hours to get the web UI where I want it to be. I highly recommend doing that _before_ running this import so that we can QA without pulling any DB copies.

**Comment by runbeyond** [comment]
I’ll follow your lead! Let me know when and what to do!!

**Comment by runbeyond** [comment]
Worked like a charm! Thanks, Colin!!
