### ISSUE TITLE
Enforce event registration availability logic

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#26]
Registration for events should only take place if event is active, registration opens at is in the epoch second past, and registration closes at is in the epoch second future.

Perform a redirect if someone tries to access the first step of the registration while it is still closed. If they make it beyond the first step, they may proceed.

**Comment by ColinW520** [comment]
@runbeyond this is implemented. Registrations can now only begin while inside the registration window. They can still _end_ while outside of the registration window. We can discuss details around the during planning.

**Comment by ColinW520** [comment]
Commit that introduced this feature: d7db1b8959205966f0dac132c26679ddda296128

**Comment by ColinW520** [comment]
This message will be displayed within 2 weeks of the end of the registration window:

![image](https://user-images.githubusercontent.com/3529146/59874127-27c86280-9363-11e9-9a49-e21b14c98eb7.png)

**Comment by runbeyond** [comment]
> @runbeyond this is implemented. Registrations can now only begin while inside the registration window. They can still _end_ while outside of the registration window. We can discuss details around the during planning.

@ColinW520 It would be great to discuss this point as I don't want to assume I know what it means.

**Comment by ColinW520** [comment]
in the example above, as long as I _start_ my registration before 12:00AM on June 30, I can finish it (ie: finish it at 12:05AM)

**Comment by runbeyond** [comment]
Got it. And all of this assumes that registrant cap hasn't already been reached, correct? If so, I approve :)

**Comment by ColinW520** [comment]
yes, it all assumes the cap hasn't been reached yet. that cap will be hard. it will completely bounce people from registration once it has been hit.

If you approve, give it a 'completed' label (may need to make one) and close it up!

**Comment by runbeyond** [comment]
Thanks, Colin!

This works great. What an awesome feature.

I tested:
- Attempting to register when the window is closed
- Registering within window
- Starting a registration before the window closes but finishing the registration after the window closes
- Verified that an encouraging banner shows on the event page (above the fold) when within two weeks of the registration window closing.
