### ISSUE TITLE
Implement automatic participant count capping

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#27]
Because computers are good at this stuff, once participants_count = participants_cap, prevent any further registrations.

 - If a user is at any part of registration, bounce them completely.
 - Don't allow the race to be selected for registration if it is full (disabled)

**Comment by ColinW520** [comment]
![image](https://user-images.githubusercontent.com/3529146/59953126-44889700-9444-11e9-80f7-54418943f3e4.png)

**Comment by ColinW520** [comment]
Important note: participants_count *does not equal* paid_participants_count. This checks against PAID participants. Not _all_ participants. IMPORTANT IMPORTANT IMPORTANT because this data model supports partial/incomplete/resumable registrations.

**Comment by ColinW520** [comment]
This is deployed and ready to be tested.

**Comment by ColinW520** [comment]
@runbeyond this can be closed once it is tested. Here are steps for testing:

 - visit an event that is in the open registration window
 - verify that you can click register on a race you know you have already subitted a complete registration for (or just submit a fresh one if you need to)
 - fill out the first step of the registration form for the individual race you selected, then STOP THERE
 - open a new tab and open the RACE ADMIN page for the race you just started a registration for
 - set the participant cap for the race to a very low number (like, 1).
 - reload the event page, check to see that the button is now disabled
 - go back to the tab you started from, and try to submit the second step of the form
 - you should be redirected back to the event page, or experience an error, SOMETHING other than proceeding

**Comment by runbeyond** [comment]
Awesome feature! Thank you, Colin. Works better than expected!
