### ISSUE TITLE
Delete Event, Location, and Race records

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#28]
As an admin user

I want to delete event, race, and location data records 

So that non-existent events, races, and locations are not visible on the website and don't unnecessarily clutter the admin dashboard.

Acceptance Criteria:
1) I can delete and event record
2) I can delete a race record
3) I can delete a location record

**Comment by runbeyond** [comment]
@ColinW520 Can we call this one done?

**Comment by ColinW520** [comment]
@runbeyond you can delete a race as long as there are no registrations. You can delete an event as long as there are no races. You can delete a location as long as there are no events.

Should be set!
