### ISSUE TITLE
Hide/Deactivate event records

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#29]
As an admin user

I want to hide or deactivate event records

So that I can keep an event and associated race records but temporarily hide them from the list of events displayed on the website

Acceptance Criteria:
1) I can hide or deactivate event records
2) Once hidden or deactivated, the event record is not visible in the main navigation events dropdown
3) Once hidden or deactivated, the event record is not visible under the events list on the main page (the list showing even cards)
4) ) Once hidden or deactivated, the event record cannot be accessed anywhere other than in the admin dashboard

**Comment by ColinW520** [comment]
If an event is deactivated, it will have a red x next to it, 
![image](https://user-images.githubusercontent.com/3529146/60036208-4a64bf00-9674-11e9-8c0f-88214864a32b.png)
and it will not show up in the dropdown,
![image](https://user-images.githubusercontent.com/3529146/60036236-5f415280-9674-11e9-8bef-9f23158d6620.png)

or the footer
![image](https://user-images.githubusercontent.com/3529146/60036253-68caba80-9674-11e9-8245-9bb038825adf.png)

(all images from dev environment)

**Comment by ColinW520** [comment]
additionally: you will have radio buttons to indicate whether or not the event is active

![image](https://user-images.githubusercontent.com/3529146/60036317-9283e180-9674-11e9-913f-b3886e8f9da9.png)


and visitors to inactive event pages (bookmarkers, old links) will be redirected

**Comment by runbeyond** [comment]
Thank you, Colin! This works as expected.
