### ISSUE TITLE
Remove FAQ section from event pages

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#30]
Please temporarily remove/hide the FAQ section from event pages. We don't have an admin UI for writing the FAQs section and we don't have time to write FAQ content ahead of site launch. Let's please hide this section and then circle back to it later when we have FAQ content and a UI to write it into the page.

**Comment by runbeyond** [comment]
@ColinW520 I'm a bad product owner! I should have written a story with acceptance criteria!!

The FAQ section is not visible on the event page but FAQ is still a section in the side navigation panel on the event page. We should remove it from the navigation panel so as not to cause confusion and to create a coherent user experience. 
<img width="1178" alt="Screen Shot 2019-06-24 at 11 41 51 AM" src="https://user-images.githubusercontent.com/44638093/60040042-54d38880-9675-11e9-9721-b6ab425aec26.png">

**Comment by ColinW520** [comment]
Missed that. Pushing an update now

**Comment by ColinW520** [comment]
@runbeyond -- ready for confirmation

**Comment by runbeyond** [comment]
Thank you, Colin! This works as expected.
