### ISSUE TITLE
Edit Homepage image

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#34]
Can we use the attached image? Also, I included a Sketch mockup.
![Spectrum website cover photo](https://user-images.githubusercontent.com/44638093/59884582-0ae95a80-9376-11e9-8319-d4239e397350.png)

**Comment by ColinW520** [comment]
@runbeyond For the sake of site speed, I try to make home page banner images load from an external site, like flickr, or somewhere backed by a CDN. Do y'all have a flickr account you could upload this to?

**Comment by runbeyond** [comment]
@ColinW520 I created Flickr account. I shared my photostream with you through the web app. If that doesn't work, the email is spectrumtrail@gmail.com (username might just be spectrumtrail) and the pw is Elizabeth%5.

**Comment by ColinW520** [comment]
@runbeyond -- this should be ready for review & close. it will be slow on first load.

**Comment by runbeyond** [comment]
Badass! Thanks, Colin!! Looks great :)
