### ISSUE TITLE
Update above the fold text on website main page

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#35]
Related to issue #31 

Please update the Text on the main page. If you can find a text similar to the mockup that would be great. Use good judgement for text size. The mockup
![Artboard](https://user-images.githubusercontent.com/44638093/59884920-e04bd180-9376-11e9-8d79-cacaee2b54d5.png)
 is not necessarily to scale so text size may not translate.

**Comment by ColinW520** [comment]
@runbeyond -- can we make the font changing part a separate issue? is it really necessary for MVP?

**Comment by runbeyond** [comment]
@ColinW520 I'll write a separate issue for the text font. Will you please remove "The Best Trail Racing in Texas"?

**Comment by runbeyond** [comment]
@ColinW520 I'll also write a separate issue for the text in the colored boxes.

**Comment by ColinW520** [comment]
@runbeyond -- should be fixed now, had to re-deploy

**Comment by runbeyond** [comment]
Thanks, Colin! This looks good.
