### ISSUE TITLE
Change color in text boxes below the fold on the main page

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#36]
Related to issues #31 and #32.

Please change the color of the text boxes below the fold (titled rugged, welcoming, and festive). The colors are in the Sketch mockup I shared via email.

**Comment by ColinW520** [comment]
@runbeyond can you please share the color hex codes? I can't open that sketch mockup.

**Comment by ColinW520** [comment]
Nvm! Got the sketch file to open.

**Comment by runbeyond** [comment]
Thanks, Colin! Looks great.
