### ISSUE TITLE
Filter Registrations by Event and Race

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#38]
As an admin user

I want to filter registrations in the admin dashboard

So that I can quickly find information about certain registrations

Acceptance Criteria
1) I can filter registrations by event
2) I can filter registrations by race

**Comment by ColinW520** [comment]
@runbeyond is this MVP?

**Comment by runbeyond** [comment]
@ColinW520 This does not have to be mvp.

**Comment by ColinW520** [comment]
@runbeyond this exists for events

![image](https://user-images.githubusercontent.com/3529146/70551664-2ec37700-1b35-11ea-9036-691fe88013ea.png)

And also for races; but, that brings you back to a view of participants.

**Comment by runbeyond** [comment]
Thanks @ColinW520! This feature is super helpful!!
