### ISSUE TITLE
Search registration records

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#39]
As an admin user

I want to search registration records

So that I can easily find a registrant's registration

Acceptance Criteria
1) I can search by first name, last name, or both

**Comment by ColinW520** [comment]
Due to the nature of the registration record (a container record, a pivot foot, etc), it makes more sense to search the participant table. Implementing there.

**Comment by runbeyond** [comment]
This is done. Great work @ColinW520 !
