### ISSUE TITLE
Facebook Pixel

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#40]
Embed Facebook Pixel on all web pages to track site traffic for re-marketing.

Embed purchases Pixel on all commerce pages to tie purchases back to specific social media marketing campaigns.

**Comment by ColinW520** [comment]
Send me the pixel code and I will get it embedded.

**Comment by runbeyond** [comment]
I emailed the facebook pixel code and instructions to your gmail address. Please let me know if you need additional information.

The most important insight we want to get out of pixel is registration completion.

**Comment by ColinW520** [comment]
> Embed Facebook Pixel on all web pages to track site traffic for re-marketing.

This part is done with #125 

The next part needs to be done with some precision and needs some testing around it. I'd like to open a new issue around that to isolate the work.

**Comment by runbeyond** [comment]
Thank you, Colin. I'll continue to monitor pixel and activity and will look to set up some time for us to review the FB business manager analytics platform that the pixel ids supposed to feed with website data.
