### ISSUE TITLE
Live Chat

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#41]
**As a:** business manager

**I want:** to chat with website customers in real time

**So that:** I can quickly and efficiently resolve customer questions and increase revenue by capturing sales while customers are on my site

*Acceptance Criteria:*

1) I can chat through a Windows, Chrome, or Mac chat app on my computer or Chromebook
2) I can chat through mobile applications
3) Conversation history is captured for all chat sessions
4) I can set availability for chat based on my own unique schedule
5) The chat feature on my website can be used as a contact form when no agent is available for live chat
6) I can scale to more chat users (agents) as necessary
7) I can plug into an AI platform through an API

**Comment by ColinW520** [comment]
@runbeyond look at Drift and at Intercom, decide who you want to pay for this!

**Comment by runbeyond** [comment]
Would the free plan from drift of any value? I don't understand what several of the features mean so I can't really tell whether it would suit our needs. I definitely can't justify more than like $5/mo for a chat service. We could spend our money more wisely on projects for this site!

**Comment by runbeyond** [comment]
Could we implement zendesk Chat? https://www.zendesk.com/chat/

There are also a few free options (I'm leery of free options. They can't always be free, right? Even when they say they are...). Also, the free options are CRM packages which we don't really need. zendesk allows us to just pay for chat.

HubSpot CRM
https://www.hubspot.com/pricing/crm

Agile CRM
https://www.agilecrm.com/multi-chat-windows

And there is my favorite platform of all: dun, dun, dun...Salesforce! $25/mo for small business CRM.
https://www.salesforce.com/solutions/small-business-solutions/overview/

Let me know what you think of zendesk

**Comment by runbeyond** [comment]
@ColinW520 Drift it is! I emailed you the JS snippet and account creds.
