### ISSUE TITLE
Customer Account Creation

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#42]
**As a:** Spectrum Trail Racing customer

**I want:** to create a customer account

**So that:** I can view my purchase history, save my registrant information and payment to make future race registration and website purchases easier

*Acceptance Criteria:*

1) I am given the option to create an account during my first race registration event
2) If I don't create an account during my first registration process, I am offered the opportunity to create an account during subsequent registration events
3) If I don't create an account during my first registration process, I am given the opportunity to permanently dismiss the prompt to create an account (Nice to have?)
4) During the account creation process, I am able to create account credentials (username and password)
5) Upon account creation, my account offers me the option to save my registrant information and/or payment information
6) If I don't save my registrant information and/or payment information during my first registration process, I am offered the opportunity to save my registrant information and/or payment information during subsequent registration events
7) If I don't save my registrant information and/or payment information during my first registration process, I am given the opportunity to permanently dismiss the prompt to save my registrant information and/or payment information
8) After creating an account, I receive a new account confirmation email
9) I can make use of username and password recovery processes

**Comment by runbeyond** [comment]
@ColinW520 Can we close this as a duplicate of issue #1 Create a signup form?

**Comment by ColinW520** [comment]
@runbeyond yes, we can
