### ISSUE TITLE
Edit Registrant Data Records

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#43]
AS a: site administrator

I want: to edit registrant data after a user has submitted their registrant form

So that: I can move registrants between race distances or change any data that may be inaccurate (e.g. email, gender, age, etc)

Acceptance Criteria:

1) I can edit any registrant information such as name, address, phone number, emergency contact, medical conditions, email, etc.
2) I can move registrants between race distances; for example, from Wonderland half-marathon to Wonderland 10k or vice versa.

**Comment by ColinW520** [comment]
@runbeyond this should probably be the _first_ thing we do after MVP as it will minimize work for you and mallory

**Comment by runbeyond** [comment]
Agreed. This and then registration cancellations and refunds???

**Comment by ColinW520** [comment]
@runbeyond they're all kind of in the same family -- manipulating of registration related data.

I think it should go like this:

0) Update the participant details, such as name, DOB, gender, etc -- just in case someone goofed or wants the start list to be corrected
1) Update the race associated with a participant/registration
2) Cancel the registration (without a refund)
3) Refund (completely) a registration
4) Refund (partially) a registration (>8 hours of work)

Partial refunds increase complexity _dramatically_.

**Comment by runbeyond** [comment]
@ColinW520 I think that all makes sense. We should talk more about the solution design and timeline once you have a chance.

**Comment by runbeyond** [comment]
Thanks, Colin! This works great.
