### ISSUE TITLE
Registration Cancellation

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#45]
**As a:** site administrator

**I want:** cancel a racer's registration

**So that:** a racer who cannot attend the race no longer shows in race registrant data reports, isn't assigned a bib number, and doesn't get loaded into our results system as an active participant who is then listed as a DNS

1) I can cancel a user's race registration
2) A cancelled race registration no longer shows in race registrant data reporting
3) The race registration transaction is still available in our historic records (for example, if we extract a data file of registrants, the cancelled registration would be included in the file and would have the status of cancelled instead of active)
4) Race registration cancellation process is separate from, but not necessarily independent from, a race registration refund process (in other words, an admin user could cancel and refund a registration at the same time)

**Comment by ColinW520** [comment]
@runbeyond this is about a 3 hour job on its own because it affects scoping queries, creating views, and adding a form to the admin view.

**Comment by runbeyond** [comment]
Noted. I think we can release the site without this feature but we can't go long without it.

**Comment by ColinW520** [comment]
This is shipped to production and ready for approval.

**Comment by runbeyond** [comment]
This works great! Thanks, Colin!!
