### ISSUE TITLE
Registration Refund

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#46]
**As a:** site administrator

**I want:** refund all or part of a racer's registration

**So that:** a racer who cannot attend the race can be refunded in part or in full if and when race policy allows

1) I can refund, in part or in full, a user's race registration
2) Race registration fees can be refunded without having to cancel a race registration
3) Refund transactions are logged as part of the race registrants transaction history
4) Race registration cancellation process is separate from, but not necessarily independent from, a race registration refund process (in other words, an admin user could cancel and refund a registration at the same time)
5) I can cancel a race registration without any refund or, during the cancellation process, I can partially refund the registration fees
6) Refunds can be entered as a percentage of the original registration amount
7) If more than one purchase was made at the time of race registration, refunds can be applied to individual products and/or race registrations

**Comment by ColinW520** [comment]
@runbeyond this is a significant lift as it is transactional with API calls. It is at least 4 hours of work by itself.

**Comment by runbeyond** [comment]
Noted. I think we can release the site without this feature but we can't go long without it.

**Comment by runbeyond** [comment]
Thanks, Colin! This works great.
