### ISSUE TITLE
Race Series Page

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#47]
Currently, the results page is not styled. I'm not sure how we can best use this page from an information hierarchy standpoint. Could this page host series and their races separate from the current event construct?

For example, if Rogue Trail Series is set up under series, would a user go there to find the races associated with the Rogue Trails series or would they still find the races under the events section of the website? 

Maybe we can hide this feature for the sake of site release and brainstorm how it fits into the information hierarchy?

**Comment by ColinW520** [comment]
@runbeyond yes, we should hide this until after release. It would be a new way to organize & show races that belong to a unique grouping that might have it's own unique marketing aspects (like series points, etc)

**Comment by ColinW520** [comment]
@runbeyond -- deployed, ready for testing & closure

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected. I do want to leverage the series concept in the near future as we can prioritize it. We have the Rogue Trail Series and the We Will Not Be Tamed series. And it would be great to leverage series concepts for bundled pricing and other promotional opportunities.
