### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#48]
There is currently a Privacy statement link in the footer of the website that doesn't link to anything. Below is our privacy statement.

Our Principles

Your privacy is paramount. We do not share any of your personal information with anyone for commercial purposes.

**Comment by ColinW520** [comment]
@runbeyond -- deployed, ready for testing & closure

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected.
