### ISSUE TITLE
Terms Statement

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#50]
There is currently a Terms link in the website footer that does not link to anything. Below is a terms statement.

Refund Policy

We can't give refunds or transfers. Once you purchase your race entry, we pay the landowners for your site use, buy your race swag, pay the insurance company,  pay the timing company and photographer,  and on. That said, we're still reasonable people and want to help you out. If you write a compelling request, we'll give you a discount to a future race.

**Comment by ColinW520** [comment]
These pages are typically <airquotes>required</airquotes> by Stripe for API processing. I'll add a static page for this.

**Comment by ColinW520** [comment]
![image](https://user-images.githubusercontent.com/3529146/60033545-62d1db00-966e-11e9-9b36-affba6bb301a.png)

**Comment by ColinW520** [comment]
@runbeyond -- deployed, ready for testing & closure

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected.
