### ISSUE TITLE
About Page Text

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#52]
Current about us text is below but needs to be overhauled! Nothing to do with this for now.

After a couple decades of racing between the two of them, Jason and Mallory Brooks have decided to partner with Rogue Running to create a new trail racing series of varying distances on some of the most rugged, beautiful Texas terrain.

**Comment by ColinW520** [comment]
@runbeyond  where does this text go?

**Comment by runbeyond** [comment]
@ColinW520 Ignore this. I started to write the text for an about page and abandoned the effort. This issue is for later when we revisit the implementation of an about page.

**Comment by runbeyond** [comment]
@ColinW520 I created issue #59 to undo this if possible.
