### ISSUE TITLE
Team Registration - MVP

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#53]
As a: Spectrum site visitor

While I am: registering for a race

I want: to designate my team name

So that: I can compete in this race on a team with friends

Acceptance Criteria:

I can enter a team name on the first step of the registration process for events that support team races.

**Comment by ColinW520** [comment]
@runbeyond this is ready for approval

**Comment by runbeyond** [comment]
@ColinW520 Trying to test this. I got through the registration process on We Will Not Be Tamed 100k relay with a couple of 500 errors. I didn't see the team option, though. I started the registration process for the circus relay but got 500 error again so I stopped there.

I just tried checking the race records to see if they need to be flagged as relays for that field to show but I get 500 error when I try to access a race record.

**Comment by ColinW520** [comment]
OK, got it, not done then :) -- working on this now

**Comment by ColinW520** [comment]
... A couple of 500 errors? That's strange... can you record yourself next time you get 500's?

**Comment by ColinW520** [comment]
@runbeyond I see the issue now. Migrations did not automatically run on the database. I just ran them.

Now you just need to follow the instructions here: http://localhost:3008/admin/dashboard

**Comment by runbeyond** [comment]
@ColinW520 I can't access the instruction at the above url. Is it because it's your local host? I'm showing my ignorance now!

I went into the circus 12-hour relay and the we will not be tamed 100k relay races and set the radio button to requires a team and then saved the records. The change doesn't save, however. When I try to register for one of the races, there is no option to provide a team name and then when I go back into the record, the radio button still shows no team required.

**Comment by runbeyond** [comment]
@ColinW520 I found the instruction on the main admin dashboard page. I cannot set reqiures team to true on event or race records.

**Comment by ColinW520** [comment]
Form doesn't seem to be persisting as expected. Could be something else. Working through the issue now. Here's what it will look like on the registration forms

<img width="597" alt="image" src="https://user-images.githubusercontent.com/3529146/60112187-fa016600-9734-11e9-96d6-4926cc94e3f1.png">

**Comment by ColinW520** [comment]
I think this just needed a fresh redeploy after the migration was run. Give it another try @runbeyond

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected. I assume we will be able to use this field during data extraction processes?
