### ISSUE TITLE
Welcoming Text Box Text

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#55]
On the homepage, there is a red text box under the main site image titled "Welcoming". Please use the following text:

The current text formatting can remain.

"Welcoming

We believe that our community is what truly makes us special. From elite speedsters, to back of the pack runners, we have a place for you at our races."

**Comment by ColinW520** [comment]
@runbeyond  Ready for approval/closure

**Comment by runbeyond** [comment]
@ColinW520 I don't see this in production.

**Comment by runbeyond** [comment]
Thanks, Colin! This looks good.
