### ISSUE TITLE
Festive Text Box Text

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#56]
On the homepage, there is a green text box under the main site image titled "Festive". Please use the following text:

The current text formatting can remain.

"Festive

From check-in to crossing the finish line, you will find yourself in a lively, festive atmosphere. Expect fresh pizza, cold beer, and live tunes."

**Comment by ColinW520** [comment]
@runbeyond  Ready for approval/closure

**Comment by runbeyond** [comment]
@ColinW520 I don't see this in production.

**Comment by ColinW520** [comment]
Try now

![image](https://user-images.githubusercontent.com/3529146/60046568-50b36500-968d-11e9-9a1b-a4a03facca9f.png)

**Comment by runbeyond** [comment]
Thanks, Colin! This looks good.
