### ISSUE TITLE
Home page above the fold font

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#57]
The font is Nanum Pen Script and is listed with Google fonts: https://fonts.google.com/?query=nanum+pen+script

**Comment by ColinW520** [comment]
@runbeyond =- deploying this now -- can you test it on mobile too?

**Comment by runbeyond** [comment]
@ColinW520 I missed this on the language/text issue card...the text above the fold should read:

"Welcome to a community of hard-working, big loving trailblazers. 
Ready to make friends and test your limits? You’re in the right place."

**Comment by runbeyond** [comment]
@ColinW520 I texted the mobile view. The font shows up on mobile as a cursive font.

**Comment by ColinW520** [comment]
@runbeyond -- deployed. should be ready to close.

**Comment by runbeyond** [comment]
@ColinW520 This looks great on the web app. Thank you! 

The mobile view is still a cursive font. It's not a terribly big deal. Would you like me to open a separate issue for the mobile font?

**Comment by ColinW520** [comment]
I have _no_ clue why it looks that way on mobile. Not all fonts are supported by all mobile devices/browsers, even if they are from google fonts. Trying to troubleshoot now by removing the fallback

**Comment by runbeyond** [comment]
I’ll try it using the google chrome app instead of safari.

**Comment by ColinW520** [comment]
@runbeyond -- give it a try now

**Comment by runbeyond** [comment]
This works! Thanks, Colin!!
