### ISSUE TITLE
Filter Registrations by Status

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#60]
As an admin user, I need to be able to filter registrations by STATUS.

Statuses:

 - *Complete*: the `completed_at` timestamp is not `nil`
 - *In Progress*: the `completed_at` timestamp is `nil`
 - *Cancelled*: the `cancelled_at` timestamp is not `nil`

**Comment by ColinW520** [comment]
This is necessary for Registration management.

**Comment by ColinW520** [comment]
@runbeyond this is ready for testing; though, you can't test 'cancelled' yet, that should be empty.

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected.
