### ISSUE TITLE
Footer about text

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#61]
Spectrum Trail Racing is a trail race production company, with a line up of eight high-end, scenic, well-marked trail races, with an after-party that is full of local flare.

**Comment by ColinW520** [comment]
@runbeyond this will be your first issue! 

Instructions: 

1) Pull down the repo
2) create a new branch (name it `jb-update-footer-text`)
3) make the necessary changes to the necessary file(hint hint)
4) commit the changes with an appropriate commit message
5) push the branch up
6) submit a PR for review.

We can walk through this together if needed; but, it's a great diving-in point so let's not miss this opportunity!
