### ISSUE TITLE
Resolve Discount Code Application Bug

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#62]
We need to be able to deal with 100% off discount codes.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/3529146/60121426-a436b900-9748-11e9-982d-4a6d73320be4.png">

When a discount code results in >= 100% off, set the amount to charge to 0. DO NOT make an API request to the stripe API. Instead, just create a payment record _without_ a stripe charge ID (update the validation).

ALL REGISTRATIONS HAVE PAYMENTS! _But not all payments have charges_

**Comment by ColinW520** [comment]
@runbeyond this is priority #1 right now

**Comment by runbeyond** [comment]
@ColinW520 yes! We have to solve this. Great catch!

**Comment by ColinW520** [comment]
@runbeyond this is ready for testing. 

1) Create a 100% off discount code if you haven't already
2) Register for any race
3) Enter the 100% off discount code
4) Enter your CC (still required, lame, I know, but things)
5) submit

🤞

**Comment by runbeyond** [comment]
Thanks, @ColinW520! This works as expected. It worked before. Was it a regression bug or something else?

**Comment by ColinW520** [comment]
@runbeyond -- it wasn't _really_ working before. It may have _looked_ like it; but, 100% off discount codes weren't fully tested; and, stripe charges were still being created for negative to 0 amounts. It would have been very, very, nasty to deal with in production.

**Comment by ColinW520** [comment]
Regarding _how_ it came about; regression is definitely a culprit here, as is my naive assumption that the stripe api could handle a charge for less than $0.50 (it cannot).

We absolutely **must** build a test suite. I am already regretting not doing so; but, with business demands rapidly evolving (and just one developer), I've let my hubris get the best of me. It should be the first thing we do once things are stabilized, and you start writing some code ;) <--- it's a fantastic way to learn how your application works.
