### ISSUE TITLE
Site Banner for Registration Downtime

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#63]
Please add a site banner to the homepage noting that registration is temporarily down until July 1st at noon while we launch our new website.

Suggested text:

Welcome to our new website! As we launch this new site, we are temporarily suspending registration for all races until July 1st at 12:00 PM Central Time US. Please peruse the new site and come back July 1st to register for some awesome races!

**Comment by runbeyond** [comment]
Baner is up on Squarespace website.

**Comment by ColinW520** [comment]
@runbeyond  Didn't see the temp text until I already wrote it. LMK if you want me to change it.

1449aef807a518b4f958ba0e3855ca25704c4a08

**Comment by runbeyond** [comment]
@ColinW520 What you put up is perfect!

**Comment by ColinW520** [comment]
@runbeyond I just put a check in there to test for an existing user. If you're logged in, you won't see this, because it's annoying.
