### ISSUE TITLE
Website cutover

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#64]
This card tracks the work inherent in switching from Squarespace to our custom website.

**Comment by ColinW520** [comment]
@runbeyond -- can you please email me your stripe keys? or text me stripe login creds. don't paste them here!

**Comment by ColinW520** [comment]
- [ ] Acquire production Froala Keys
 - [ ] Set production Stripe keys
 - [ ] Change email host
 - ... more to come

**Comment by runbeyond** [comment]
Do you need anything else from me re: keys of any kind?

**Comment by ColinW520** [comment]
@runbeyond don't think so. should be set.

**Comment by ColinW520** [comment]
@runbeyond this should be ready to close. Please open a new issue to specifically address transferring the domain.

**Comment by runbeyond** [comment]
Thanks, Colin! This works as expected. Closing and opening and new issue.
