### ISSUE TITLE
Show all registration data fields

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#66]
This is necessary for validating #25 works as expected, and, for sanity's sake while we watch new registrations come in.

We need to be able to see individual Registrations and their associated data tables, like payments, participants, etc.

This will be the SHOW action on the Registrations controller

We will also need an index view for Participants

We will also need to update the event and race views to link to specific subsections of registrants.

**Comment by ColinW520** [comment]
@runbeyond -- this will be approveable once the import is done. assigning to you now so I don't forget.

**Comment by runbeyond** [comment]
This is fucking sweet! Amazing work, Colin!

@ColinW520
