### ISSUE TITLE
Start List error

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#67]
When I try to access a start list for a race that has associated registration records, I receive a 500 error message. This only happens with races that have associated registration records.

**Comment by ColinW520** [comment]
@runbeyond resolved?

![image](https://user-images.githubusercontent.com/3529146/60368983-d863e100-99b7-11e9-9736-3fed01822a6e.png)

**Comment by runbeyond** [comment]
Works as expected.
