### ISSUE TITLE
Create an admin interface showing emails sent

### ISSUE THREAD

**Issue by ColinW520** [spectrumtrail/spectrum#7]
As an admin I want to be able to see who was sent what email.

This will aid in troubleshooting for accounts, registrations, payments, receipts, confirmations, etc.

**Comment by runbeyond** [comment]
@ColinW520 SendGrid provides this service; however, they only offer 3 days of history on our current plan. They offer 30 days of history if we pay $5/mo. If we want more than 30 days (which I think we can do) we can use SendGrid's [Event Webhook](https://sendgrid.com/docs/for-developers/tracking-events/event/) to store emails in our own system. You may know all of this or it may have a different solution in mind but I thought I'd share what I saw.

**Comment by runbeyond** [comment]
@ColinW520 We have a v1 for this feature. Can we call this done for now?
