### ISSUE TITLE
Ordering race distances on Homepage event cards

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#71]
What logic sorts the order of the races on the event cards? On some event cards, the races are in ascending order and others they are in descending order. Some are words and some numbers which probably complicates a consistent ordering??? If possible, a descending order would be ideal, eventually...

**Comment by ColinW520** [comment]
Right now, the only logic is creation ID. With some races being numbers, and others being words, that does complicate things. I'll apply an alpha sort and it will at least be consistent that way.

**Comment by runbeyond** [comment]
Thanks, Colin!
