### ISSUE TITLE
Race registrations chart/graph

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#74]
As a Spectrum Admin user

I want to see registrations per event in my main analytics dashboard

So I can easily track registration progress across event

Acceptance Criteria
We can view registrations by race in the races view of the admin dashboard so that granularity may not be necessary for the main dashboard view and may only complicate a simple/useful analytics dashboard view.

**Comment by runbeyond** [comment]
@ColinW520 We have a v1 on this feature. Can we call this done for now?

**Comment by ColinW520** [comment]
yes, for now!
