### ISSUE TITLE
Email address on website

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#75]
As a business owner

I want my email address included in the website footer

So that customers can contact me with business inquiries

Acceptance Criteria
Please use malloryalexis@gmail.com

**Comment by runbeyond** [comment]
@ColinW520 Can we lease treat this as high priority :) ?

**Comment by ColinW520** [comment]
![image](https://user-images.githubusercontent.com/3529146/61924873-f2e19980-af26-11e9-88e8-1b498ffe218c.png)

**Comment by ColinW520** [comment]
This has been implemented as a link and shipped to production.

**Comment by runbeyond** [comment]
Thanks, Colin!
