### ISSUE TITLE
Temporarily Archive/Hide Escarpment Training Camp

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#76]
We are likely to change this to a high altitude training camp in Buena Vista, CO...

**Comment by ColinW520** [comment]
@runbeyond you can do this by simply unchecking the 'active' box on the events form

![image](https://user-images.githubusercontent.com/3529146/62594628-8062a900-b898-11e9-9086-1fb31624b87d.png)

**Comment by runbeyond** [comment]
Good call! Done. Thanks, Colin.
