### ISSUE TITLE
Cancelation Confirmation Email

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#77]
As a Spectrum customer

I want to receive a race cancellation confirmation email when my race registration is cancelled

So that I can be sure my race has been cancelled

Acceptance Criteria:
User receives conf email.
One generic email for al cancelations including those that are refund eligible

**Comment by runbeyond** [comment]
I have to write the confirmation email text before we can develop this.

**Comment by ColinW520** [comment]
This would be a good thing for me to knock out this week

**Comment by ColinW520** [comment]
> write the confirmation email text before we can develop this.

Do you have this text? Or, better yet, now that you've done some cancellations -- are you sure you want this email auto sent? Why not just save a template and send it manually so you can deal with any externalities presented by the customer?

**Comment by runbeyond** [comment]
We can go ahead and build the template and send it manually for now. I'll close this and we can address it in the future if necessary (if the volume of work becomes too much).
