### ISSUE TITLE
Reg. Checkout Error Message

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#79]
I'm not sure if this constitutes a bug in the truest sense...When a user competes the registration payment step to purchase the last available race entry, the user receives the attached error message. The user's payment is successful and the user receives a confirmation email but the experience is confusing and users reach out to us asking for further confirmation.

Steps to recreate:
Register for a race that has only one remaining participant spot. 
Compete the registration process all the way through payment confirmation.

Expected Behavior:
I receive payment confirmation
I receive registration confirmation email

Actual Behavior:
I receive payment confirmation
I receive the attached error message (which contradicts payment confirmation)
I receive registration confirmation email (which contradicts error message)

<img width="340" alt="Screen Shot 2019-08-05 at 9 27 04 PM" src="https://user-images.githubusercontent.com/44638093/62538635-8614ac00-b810-11e9-8267-beb2738c0c42.png">

**Comment by ColinW520** [comment]
They are receiving this error message if they are the _last_ person into the race, so the confirmation step is saying 'oh wait, you're done!' -- i'll add a +1 to that check.

**Comment by ColinW520** [comment]
8ce6872c1a8239ace593ba0b5c6e296212039631 should resolve this

**Comment by runbeyond** [comment]
Nice work! Thanks for adding the reference to the code changes. I like looking and seeing if I can figure out what you did!

I’ll test as soon as possible.

**Comment by ColinW520** [comment]
@runbeyond -- this should be resolved.

**Comment by runbeyond** [comment]
I've been reluctant to test this in production. I'll close it now. We will probably let at least one more person that we know sign up for sky island and I'll ask them to pay attention to this.
