### ISSUE TITLE
Update sender email for Reg. Conf. Email

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#82]
We no longer have access to contact@spectrumtrailracing.com

Pease update sender email to mallory@spectrumtrailracing.com

mallory@spectrumtrailracing.com should also be the reply to email address

**Comment by ColinW520** [comment]
https://github.com/spectrumtrail/spectrum/commit/e6f730194b05011a968edc830f4cc0eaecbfe195 Done~!

**Comment by runbeyond** [comment]
Thanks, Colin! I haven't tested it by registering but the code looks goos!!
