### ISSUE TITLE
Race Team Page Layout

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#87]
Please implement the attached team page layout.

Our Team

The People who run with Spectrum not only share the vision and values of our community, they embody it.

We are ambassadors to the sport. We are mentors. We are competitors. We are family.

Leadership

Mallory Brooks
Founder l Race Director

Jason Brooks
Founder l Race Director

Jonathan Garner
Team Captain

The Trail Blazers

see attached google doc: https://docs.google.com/document/d/1a5LzfbxHW1IAdO1zNgS0kmh6fSYqhZjMb0gjNCM3iBU/edit#

**Comment by runbeyond** [comment]
@ColinW520 I'll keep adding text to the comment box above as I put it all together.

**Comment by runbeyond** [comment]
[Race Team.pdf](https://github.com/spectrumtrail/spectrum/files/3531116/Race.Team.pdf)
![DJ Mallory](https://user-images.githubusercontent.com/44638093/63533998-ac566f00-c4d3-11e9-86e9-d584afa2d562.jpg)
![JGarner](https://user-images.githubusercontent.com/44638093/63533999-ac566f00-c4d3-11e9-9996-837625b0d073.jpeg)
![Mallory on stilts](https://user-images.githubusercontent.com/44638093/63534000-ac566f00-c4d3-11e9-9009-ed8d780490a5.jpg)

![Wendling portrait](https://user-images.githubusercontent.com/44638093/63534074-e3c51b80-c4d3-11e9-9b62-2eada27b131b.jpg)

**Comment by runbeyond** [comment]
![McElvain Portrait](https://user-images.githubusercontent.com/44638093/63543760-247b5f80-c4e9-11e9-93a3-b792e5d89c18.jpg)
![Moore Portrait](https://user-images.githubusercontent.com/44638093/63543761-247b5f80-c4e9-11e9-8dcb-fad2e8b5de8e.jpeg)
![ScottTowle Portrait](https://user-images.githubusercontent.com/44638093/63543766-29401380-c4e9-11e9-96e6-cede0eef6586.jpg)
![Wendling portrait](https://user-images.githubusercontent.com/44638093/63543767-29401380-c4e9-11e9-8555-22e7b06be78c.jpg)
![AllenDaniel Portrait](https://user-images.githubusercontent.com/44638093/63543782-31984e80-c4e9-11e9-830e-8a4ec9cd038d.jpg)
![AmyTiscareno Portrait](https://user-images.githubusercontent.com/44638093/63543785-3230e500-c4e9-11e9-87b2-3f25aa08075e.jpeg)
![Beckham Portrait](https://user-images.githubusercontent.com/44638093/63543786-32c97b80-c4e9-11e9-9f48-b8a1b4c0c701.png)
![JJTiscareno Portrait](https://user-images.githubusercontent.com/44638093/63543793-38bf5c80-c4e9-11e9-8d42-d1c07505fff2.jpeg)
![KatieTowle Portrait](https://user-images.githubusercontent.com/44638093/63543794-3957f300-c4e9-11e9-9a85-b4234439fbec.jpg)
![Kimbrough Portrait](https://user-images.githubusercontent.com/44638093/63543796-39f08980-c4e9-11e9-9bc0-c85bcd106104.jpg)
![Kurvach Portrait](https://user-images.githubusercontent.com/44638093/63543801-3a892000-c4e9-11e9-97d1-6da490f5b14e.jpg)

**Comment by runbeyond** [comment]
@ColinW520 Can we add social handles under each team members card on the main team landing page? I'm thinking Strava and Instagram for those who are one or both. I'll update the mock up to include this.

**Comment by runbeyond** [comment]
![Race Team Landing Page](https://user-images.githubusercontent.com/44638093/70558977-7d7c0b80-1b4b-11ea-8a8a-1896584b8d9e.png)
![Uploading Mallory's Individual Team Member's Page.png…]()

**Comment by ColinW520** [comment]
@runbeyond can we close this card, and open a new one for any modifications (iterations) to the existing design/layout?

**Comment by runbeyond** [comment]
Thank you, @ColinW520 and @willblake01 for your work on this project! I'm excited to have this piece up on the website and be able to promote it!!
