### ISSUE TITLE
Add data field to race team member records for social media links

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#88]
Please add data fields on race team member records so that we can include strava and instagram links for each team member to grow their audiences.

**Comment by ColinW520** [comment]
@willblake01 's work in #104 addesses this.

**Comment by runbeyond** [comment]
@ColinW520 @willblake01 These fields exist; however, there are a few things to work on:

1) The fields should be optional as not all race team members are on one or the other platform, so we should show these icons only where applicable.
2) The icons are left justified in the team member card where there should be centered for stylistic purposes.
3) If, for example, the Strava field has the team member's Strava profile link but the instagram field is empty, the instagram field becomes clickable in the landing page UI but links back to the spectrum website. It shouldn't be clickable if the field isn't populated with a URL.

**Comment by runbeyond** [comment]
Moving back to in progress

**Comment by ColinW520** [comment]
@runbeyond 



> 1. The fields should be optional as not all race team members are on one or the other platform, so we should show these icons only where applicable.

The fields are optional both in the DB and the Form; however, they do show up whether entered or not, so presentational logic will need to be introduced. Great opportunity for @willblake01 to learn about Decorators!

> 2. The icons are left justified in the team member card where there should be centered for stylistic purposes.

This is fixed as of this morning.

> 3. If, for example, the Strava field has the team member's Strava profile link but the instagram field is empty, the instagram field becomes clickable in the landing page UI but links back to the spectrum website. It shouldn't be clickable if the field isn't populated with a URL.

This will be fixed with resolution to item 1 above. 

resolution: if the team member does not have the social profile, do not show the link! got it.

**Comment by ColinW520** [comment]
@runbeyond just deployed some code to address this

**Comment by ColinW520** [comment]
@runbeyond are we good to close this?
