### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#91]
Our website has traditionally been a key source of newsletter subscriptions. We need a way to collect new members through our website such as a newsletter sign up for and/or newsletter pop up.

**Comment by runbeyond** [comment]
I need to research what is possible using SendGrid. I imagine there is an API solution or perhaps something even easier/different/better...

**Comment by ColinW520** [comment]
Where is the newsletter sent from? This is easy to implement. Just tell me where to send/collect the addresses. If you would like the stored on the site itself, that is also an option.

**Comment by runbeyond** [comment]
I'd like to use SendGrid as the newsletter email repository. I'm not sure what is possible but I'll do some research on it now.

**Comment by runbeyond** [comment]
I'm not sure whether an embedded form or a button would be better for the signup form. 

**Option A**
I created a signup form in SendGrid and styled it to maybe match the website. Here is the embed code for the signup form: <iframe src="https://cdn.forms-content.sg-form.com/a6949964-1329-11ea-901d-728295ace1fb"/>

And here is a landing page link if we just want to add a signup button as opposed to an embedded form: https://cdn.forms-content.sg-form.com/a6949964-1329-11ea-901d-728295ace1fb

**Option B**
It look slike SendGrid has a free subscription widget that requires adding a provided script of html and js. I'm not sure what it would look like or whether we would have to add some styling to note that the widget as it appears is a newsletter sign up form.

https://sendgrid.com/blog/building-a-sendgrid-subscription-widget/

**Comment by runbeyond** [comment]
@ColinW520 This is probably our top priority. Our website has traditionally been our primary way to consistently grow our email marketing base. That is, outside of special events or target SM ads, our website allows for continuous passive growth of email subscribers. Because we haven't had this feature, over the past year, we have net atrophied email subscribers through unsubscribes every time we send a newsletter. In the previous comment, I included the available solution options from SendGrid. Is this something ew can work on in the near future? Is this something @willblake01 could tackle? Or that maybe even I could tackle?

**Comment by willblake01** [comment]
@runbeyond I think I could easily get the sendGrid option up and working. It's probably worth going over the tradeoffs between that and storing on the site as @ColinW520 mentioned before doing any work.

**Comment by runbeyond** [comment]
@willblake01 Thanks! I'd love to make progress on this. Can you put your thoughts on the tradeoffs in this thread? And maybe provide a. few details on the implementation solution? Thanks!

**Comment by willblake01** [comment]
Tradeoffs:
It would be more work up front to collect the addresses on our site. There would be some time cost involved in building out the solution vs dropping in the SendGrid solution. On the other hand it would avoid relying on another dependency which is always a good thing. SendGrid could make breaking changes, start charging, get deprecated, or some other bs for example. This would be a pretty easy solution to build out so I think the cost to do this in-house would be fairly low.

Implementation:
I would think all we would need to do is build a form for the front-end that makes a post request to the back-end that collects the signup emails on the database. I'd have to do some research on how to automate the emails sending for the newly signed up users but we're already using some gems that should be able to accomplish this. I'm more than happy to write up a more detailed strategy if we want to go this route.

**Comment by runbeyond** [comment]
@willblake01 I'd prefer to rely on Sendgrid to store contact info since that's what we're already using to store contact lists and send marketing emails. We're also already using SendGrid API solutions to send registration confirmation emails.

**Comment by willblake01** [comment]
👍 I think I could figure out how to get that working with the form from option A above.

**Comment by runbeyond** [comment]
Let’s do it!

**Comment by willblake01** [comment]
@runbeyond Any thoughts on placement? I'm testing it on the landing page but there's a lot of options. Also, that decision might affect if using the form or widget works better with the design.

**Comment by runbeyond** [comment]
I don’t know what is possible. Ideally, we could have 1) a pop up form for
new visitor, and 2) an embedded signup for at the bottom of the homepage
(exact placement to be discussed), and 3) a sign up opportunity at the end
of the registration process (Colin would have to do this).

Can you elaborate on the trade offs for the various implementation
solutions?

**Comment by willblake01** [comment]
Ok, sweet, I like those ideas. My concern was the form was kind of large and imposing to be featured towards the top. The widget was a little more design friendly for the meat of the landing page. In my mind tradeoffs would be the larger form might command some people's attention to sign up but scare others away and the smaller widget might get some people if nested in the right spot but also might get overlooked. I think your suggestion above is perfect to maximize signups without being too pushy. I tested out the form towards the bottom of the landing page just under the promo video and above the sponsors just to get a first look, we can easily move it.

![image](https://user-images.githubusercontent.com/16193879/82765305-4046c580-9ddb-11ea-998b-499efc63e8a1.png)

![image](https://user-images.githubusercontent.com/16193879/82765309-4a68c400-9ddb-11ea-9a1f-75f77f1180a3.png)

![image](https://user-images.githubusercontent.com/16193879/82765312-52c0ff00-9ddb-11ea-833c-d42a0c4ef116.png)

**Comment by willblake01** [comment]
@runbeyond @ColinW520 Per our conversation at Camp Elevation I removed the modal and only have the signup form rendering on the bottom of the landing page on first site visit based on a cookie.

Jason - any further thoughts on adding a background to the section the form is in?

**Comment by runbeyond** [comment]
Thanks, Will.

The next step is for us to get on a screen share and took a look at what
you have so you can ask questions and I can provide feedback on your
progress. Background styling is a great question and I think we should
explore that and any other questions/ideas you have.

I have time Tuesday and Wednesday morning if you have any availability in
there.

-JB

**Comment by runbeyond** [comment]
@willblake01 Can you walk me through the final solution for this issue? I'd like to see it from the standpoint of the end user.

**Comment by runbeyond** [comment]
Thanks, @willblake01!
