### ISSUE TITLE
Race Registration Status

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#92]
Registration statuses aren't updating appropriately on event pages. 

Sky Island:
- Both races are sold out
- Registration status reads - "Better hurry! Registration closes soon! You have until September 22, 2019 12:00am CDT"

Wonderland
- I changed all races to sold out (by making the available registration spots less than current registrants)
- Registration Status show normal (see attached photo)
<img width="1440" alt="Screen Shot 2019-09-08 at 2 50 26 PM" src="https://user-images.githubusercontent.com/44638093/64493677-a1783a00-d248-11e9-828e-8fcfb68c83fc.png">
<img width="1440" alt="Screen Shot 2019-09-08 at 2 44 01 PM" src="https://user-images.githubusercontent.com/44638093/64493680-a6d58480-d248-11e9-8d9d-d232f3936cb1.png">

**Comment by ColinW520** [comment]
This appears to be errant _display_ logic, will resolve.

**Comment by ColinW520** [comment]
Should be resolved by 113cfd5eb1d1eb3e33ca57e6a4f962a2227ab887

**Comment by runbeyond** [comment]
Thank you, Colin! This is working again. Great work!
