### ISSUE TITLE
Gender Identity

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#95]
I think we should change Men's Open and Women's Open to Male and Female on the Gender Identity question in the registration process. Men's Open and Women's Open is easily confusing.

**Comment by ColinW520** [comment]
This is done!

**Comment by runbeyond** [comment]
@ColinW520 I didn't see the update in production when I registered for the vagabond time trials.
<img width="608" alt="Screen Shot 2019-10-01 at 10 41 12 AM" src="https://user-images.githubusercontent.com/44638093/65984423-5fa47300-e445-11e9-861a-23c6c6a5fcf2.png">

**Comment by runbeyond** [comment]
@ColinW520 I assigned this back to you. Please see above comment.

**Comment by runbeyond** [comment]
Thanks, Colin! This looks great.
