### ISSUE TITLE
Add Medium blog to Spectrumtrailracing.com

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#97]
I created a medium blog in hopes that we can just integrate it with the Spectrum website ni some way like linking from main navigation or something like that.

https://medium.com/spectrum-trail-racing

**Comment by ColinW520** [comment]
@runbeyond this is another one I must not have seen. My apologies! Just drowning in GH issue emails now as my new job using GH issues as well. I will add this to the site's header and footer right away. Please let me know if you want it anywhere else.

**Comment by runbeyond** [comment]
Thanks, Colin!
