### ISSUE TITLE
Add a link to Rogue Running

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#98]
Spectrum is trying to tap its audience to help grow our Rogue Running trail training group. To help this effort, we would like to add a link to the Rogue Running website resources related to trail training.

Should we add a main navigation link that links to the Rogue Running website or should we add a page that outlines the program and then links out the Rogue Running website? Or should we follow some other approach?

Link to Rogue Running website: https://www.roguerunning.com/trail

**Comment by ColinW520** [comment]
@runbeyond this is the first time I'm seeing this. With the start of my new job, I'm drowning in Github emails. 

Regarding your question, the answer is **both**.

For now, I will add a link to the main nav of the site, and the footer nav. It will say `Training` and it will link to the given link. In the future, we can create a page to outline the benefits of the program.

**Comment by runbeyond** [comment]
Thanks, Colin!
