### ISSUE TITLE
Add results calendars to website

### ISSUE THREAD

**Issue by runbeyond** [spectrumtrail/spectrum#99]
We're using a new results platform from Race Roster. They have the concept of race calendars that we can use to embed results on our website. 

We have a couple of options:

1) We can embed iframe with results on individual event pages
2) We can create a results link in the main navigation with sub-links to each year's race calendar

Here is the 2019/2020 results calendar code snippet: <iframe src="https://timer.raceroster.com/Calendars/L6crPG2qbgq2eCkzWNVMdUF" id="raceroster" style="border:none; height:700px; width:100%"></iframe>

**Comment by ColinW520** [comment]
I think option 1 would make the most sense. Where on the individual events' page would you like this to be?

**Comment by ColinW520** [comment]
@runbeyond need more data here. Need placement, and, relevant embed codes from RaceRoster

**Comment by ColinW520** [comment]
To iterate on this, I would like to propose the following

1) Create a new section in the events menu, immediately under the 'overview' section. Name it "results"
2) This section will be an HTML input, so you can build results table the way you want it for each event -- or -- embed a RaceRoster embeddable.

In the future, I want to be able to do this as an association with Participants, created via API, but we're a few dozen steps away from that now.

_So how about we proceed with the first two steps there above?_

**Comment by runbeyond** [comment]
@ColinW520 Lets try it out. What do we need to do?

**Comment by runbeyond** [comment]
This works great! Thank you.
